messages:
  spawnerAmountOnRightClick: '&bSpawners &8&m>&f There are <amount> <entitytype> Spawners'
  cannotPlaceSpawner: '&cYou cannot place a spawner within <radius> blocks of another one!'
  mobcoinObtainActionBar: '&b+<amount> coins'
  totalXp: '&bYou have <exp> experience'
  totalCoins: '&bYou have <amount> coins'
  notEnoughXp: '&cYou do not have enough xp!'
  notEnoughCoins: '&cYou do not have enough coins!'
  buyItem: '&bYou bought a <item> for <amount> coins.'
  notValidPlayer: '&c<player> is not a valid player!'
  notValidNumber: '&c<amount> is not a valid amount!'
  playerTotalCoins: '&b<player> has <amount> coins'
  notPlayer: '&cYou are not a Player!'
  help:
    - '&8---------------'
    - '&bRetronixCoins Commands:'
    - '&b/coins [player]'
    - '&b/coins pay [player] [amount]'
    - '&b/coins shop'
    - '&b/coins top'
    - '&8---------------'
spawners:
  #set to 0 to disable
  radius: 5
  #spawnerAmountOnRightClick message
  messageEnabled: true
  placementNerfEnabled: true
  disableMobAIOnSpawn: true
xpToCoinShop:
  enabled: true
  icon:
    material: EXPERIENCE_BOTTLE
    amount: 1
    data: 0
    name: ''
    lore: []
  #rates are: level:coin
  conversionRates:
    - 30:2
    - 50:8
    - 100:50
coinTop:
  #GUI or TEXT
  type: GUI
  enabled: true
coinShop:
  mainMenu:
    name: '&8&nCoin Shop'
    rows: 4
    fills:
      '1':
        material: STAINED_GLASS_PANE
        amount: 1
        data: 8
        name: ' '
        lore: []
        slots:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 9
          - 10
          - 11
          - 12
          - 13
          - 18
          - 19
          - 20
          - 21
          - 27
          - 28
          - 29
          - 30
      '2':
        material: STAINED_GLASS_PANE
        amount: 1
        data: 8
        name: ' '
        lore: []
        slots:
          - 5
          - 6
          - 7
          - 8
          - 14
          - 15
          - 16
          - 17
          - 22
          - 23
          - 24
          - 25
          - 26
          - 31
          - 32
          - 33
          - 34
          - 35
mobDrops:
  RABBIT:
    1:
      material: RABBIT
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: RABBIT_HIDE
      amount: 1-1
      chance: 10
      canBeCooked: false
      data: 0
  CHICKEN:
    1:
      material: RAW_CHICKEN
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: FEATHER
      amount: 1-1
      chance: 50
      canBeCooked: false
      data: 0
  PIG:
    1:
      material: PORK
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
  SHEEP:
    1:
      material: MUTTON
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: WOOL
      amount: 1-1
      chance: 50
      canBeCooked: false
      data: 0
  COW:
    1:
      material: RAW_BEEF
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: LEATHER
      amount: 1-1
      chance: 50
      canBeCooked: false
      data: 0
  CREEPER:
    1:
      material: SULPHUR
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
  ZOMBIE:
    1:
      material: ROTTEN_FLESH
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
  WITCH:
    1:
      material: REDSTONE
      amount: 0-2
      chance: 100
      canBeCooked: false
      data: 0
  SPIDER:
    1:
      material: STRING
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: SPIDER_EYE
      amount: 0-1
      chance: 50
      canBeCooked: false
      data: 0
  SKELETON:
    1:
      material: BONE
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: ARROW
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  IRON_GOLEM:
    1:
      material: IRON_INGOT
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: RED_ROSE
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  BLAZE:
    1:
      material: BLAZE_ROD
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
  PIG_ZOMBIE:
    1:
      material: ROTTEN_FLESH
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: GOLD_INGOT
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  ENDERMAN:
    1:
      material: ENDER_PEARL
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  SILVERFISH:
    1:
      material: NETHER_STAR
      amount: 1-1
      chance: 100
      canBeCooked: false
      data: 0
xP:
  RABBIT: 1-3
  CHICKEN: 1-3
  PIG: 1-3
  SHEEP: 1-3
  COW: 1-3
  CREEPER: 5-5
  ZOMBIE: 5-5
  WITCH: 0-2
  SPIDER: 5-5
  SKELETON: 5-5
  IRON_GOLEM: 0-0
  BLAZE: 10-10
  PIG_ZOMBIE: 5-5
  ENDERMAN: 5-5
  SILVERFISH: 1-3