name: RetronixMobcoins
version: 1.1
main: net.retronixmc.mobcoins.Main
authors: [WeChanDoIt]
description: Mobcoin Plugin!
softdepend: [SuperiorSkyblock2]
commands:
  coins:
    description: Coins command
    aliases: [mobcoins, retronixmobcoins]
  mobcoingenerators:
    description: MobCoin Generator Command
    aliases: [mg, mcgenerator, mcg]