name: RetronixCoins
version: 1.1
main: net.retronixmc.coins.Main
authors: [WeChanDoIt]
description: Mobcoin Plugin!
softdepend: [UltimateStacker]
api-version: 1.15
commands:
  coins:
    description: Coins command
    aliases: [retronixcoins, retrocoin, retronixcoin, coin, mobcoin, mobcoins]